### ISSUE TITLE
One reaction button crash

### ISSUE THREAD

**Issue by Alexinzaz** [pgreze/android-reactions#16]
Hello. If i want to add only one reaction buton I have a crash.

`2020-05-20 09:20:56.986 7096-7096/? E/MessageQueue-JNI: java.lang.ArithmeticException: divide by zero
        at com.github.pgreze.reactions.ReactionViewGroup.<init>(ReactionViewGroup.kt:56)
        at com.github.pgreze.reactions.ReactionPopup$view$2.invoke(ReactionPopup.kt:30)
        at com.github.pgreze.reactions.ReactionPopup$view$2.invoke(ReactionPopup.kt:17)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at com.github.pgreze.reactions.ReactionPopup.getView(Unknown Source:2)
        at com.github.pgreze.reactions.ReactionPopup.onTouch(ReactionPopup.kt:55)
        at android.view.View.dispatchTouchEvent(View.java:12523)`

**Comment by pgreze** [comment]
@Alexinzaz better late than never, I just released a new version 1.2.2 with a fix for this crash.
Hope it can be helpful :)

**Comment by Alexinzaz** [comment]
thank you very much!
